### PR TITLE
Empty elements and collections

### PR DESCRIPTION
**Pull request by bwetherfield**
@jsbean, can you take a look at this - especially the change to BorderTest? My take is that the reading of `Border?` is ambiguous there and that either `Border()` or `nil` is a valid interpretation, but it does mean that I am changing the output of an existing test, which feels like something that should be discussed.

### CODE REVIEW

**Review by jsbean — COMMENTED** [review]
I think these points are all valid. I have to say, I am not expert enough to know what the expectations should be here.

All in all, I think this looks good!

**Comment by jsbean** [comment]
@bwetherfield, are you cool with merging at this point? I feel fine with it!

**Comment by jsbean** [comment]
BTW, this enables us to parse two more LilyPond test files successfully.

**Comment by bwetherfield** [comment]
Oki doke in we go!

**Pull request merged**
